version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --config /database.yaml --config /init.yaml --masterkey "${ZITADEL_MASTERKEY}" --tlsMode disabled'
    ports:
      - "8080:8080"
    volumes:
      - "./database.yaml:/database.yaml:ro"
      - "./init.yaml:/init.yaml:ro"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sso
      - PGADMIN_DEFAULT_EMAIL=teamsupareel@gmail.com
      - ADMIN_DEFAULT_USER=admin
      - ADMIN_DEFAULT_PASSWORD=postgresAdmin
    ports:
      - "5432:5432"
    networks:
      - "zitadel"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "sso"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
    volumes:
      - "pgdata:/var/lib/postgresql/data:rw"

networks:
  zitadel:

volumes:
  data:
